
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    API_KEY: 'AIzaSyBhhm2EciBsETcQpPngSOKlq454vmrG06U',
    DB_URL: 'https://ng-course-my-recipes-default-rtdb.asia-southeast1.firebasedatabase.app/recipes.json'
  };
